# prometheus config file yaml backup
global:
  scrape_interval: 15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

alerting:
  alertmanagers:
    - static_configs:
        - targets:

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:

scrape_configs:
  - job_name: "arm-selector"
    scheme: https
    static_configs:
      - targets: ["arm-selector.onrender.com"]

  - job_name: "model-trainer"
    scheme: https
    scrape_interval: 120s

    static_configs:
      - targets: ["model-trainer.onrender.com"]

  - job_name: "reward-predictor"
    scheme: https
    static_configs:
      - targets: [ "reward-predictor.onrender.com" ]

  - job_name: "rewards-service"
    scheme: https
    static_configs:
      - targets: [ "reward-service.onrender.com" ]

  - job_name: "experiment-params"
    scheme: https
    static_configs:
      - targets: [ "experiments-params.onrender.com" ]